from enum import IntEnum, StrEnum


class PerceptionFailureCode(StrEnum):
    OK = "OK"
    OCCLUDED = "OCCLUDED"
    OUT_OF_VIEW = "OUT_OF_VIEW"
    DEPTH_INVALID = "DEPTH_INVALID"
    MULTIPLE_CANDIDATES = "MULTIPLE_CANDIDATES"
    CALIB_INVALID = "CALIB_INVALID"
    TRACK_JUMP_REJECTED = "TRACK_JUMP_REJECTED"
    REACQUIRE_FAILED = "REACQUIRE_FAILED"


class TrackingStatus(StrEnum):
    TRACKING = "TRACKING"
    LOST = "LOST"
    RELOCALIZING = "RELOCALIZING"
    REACQUIRING = "REACQUIRING"


class SkillName(StrEnum):
    PICK = "PICK"
    PLACE = "PLACE"


class PhaseId(IntEnum):
    RESET = 0
    APPROACH_PREGRASP = 1
    ALIGN = 2
    DESCEND_GRASP = 3
    CLOSE = 4
    LIFT = 5
    VERIFY_GRASP = 6
    TRANSIT_PREPLACE = 7
    DESCEND_PLACE = 8
    OPEN = 9
    RETREAT = 10
    DONE = 11
    RECOVER_RETRY_APPROACH = 20
    RECOVER_RETRY_DESCEND = 21
    RECOVER_REGRASP = 22


class SkillOutcomeState(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    UNCERTAIN = "UNCERTAIN"


class SkillFailureCode(StrEnum):
    TIMEOUT = "TIMEOUT"
    NO_PROGRESS = "NO_PROGRESS"
    NO_GRASP = "NO_GRASP"
    DROP_DETECTED = "DROP_DETECTED"
    PLACE_MISS = "PLACE_MISS"
    UNSAFE_ABORT = "UNSAFE_ABORT"


class SafetyReflexReason(StrEnum):
    JOINT_LIMIT = "JOINT_LIMIT"
    WORKSPACE_LIMIT = "WORKSPACE_LIMIT"
    COLLISION_RISK = "COLLISION_RISK"
    OVERCURRENT = "OVERCURRENT"
    ESTOP = "ESTOP"


class SafetyState(StrEnum):
    OK = "OK"
    FAULT = "FAULT"


class ActStatus(StrEnum):
    IDLE = "IDLE"
    RUNNING = "RUNNING"
    BUFFER_LOW = "BUFFER_LOW"
    STALE = "STALE"


class CommandType(StrEnum):
    START_SKILL = "START_SKILL"
    ABORT_SKILL = "ABORT_SKILL"
    OVERRIDE_TARGET = "OVERRIDE_TARGET"
    REQUEST_PERCEPTION_REFRESH = "REQUEST_PERCEPTION_REFRESH"


class CommandAckStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED_STALE = "REJECTED_STALE"
    REJECTED_WRONG_SKILL_RUN = "REJECTED_WRONG_SKILL_RUN"
    ALREADY_APPLIED = "ALREADY_APPLIED"
